In [3]:
my_list=[1,2,3]

In [4]:
import numpy as np

In [5]:
print(my_list)

[1, 2, 3]


In [9]:
array = np.array(my_list)
array

array([1, 2, 3])

In [10]:
my_matracis = [[1,2,3],[4,5,6],[7,8,9]]
my_matracis

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.zeros(4)

array([0., 0., 0., 0.])

In [23]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.linspace(0,4,2)

array([0., 4.])

In [28]:
np.linspace(0,4,3)

array([0., 2., 4.])

In [29]:
np.linspace(0,6,4)

array([0., 2., 4., 6.])

In [35]:
np.linspace(0,6,3)

array([0., 3., 6.])

In [36]:
np.linspace(0,4,6)

array([0. , 0.8, 1.6, 2.4, 3.2, 4. ])

In [37]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [47]:
np.random.rand(10)

array([0.54617344, 0.69940373, 0.15429764, 0.95616128, 0.80064836,
       0.19922837, 0.75135866, 0.50079594, 0.93226046, 0.59491654])

In [41]:
np.random.rand(4,5)

array([[0.81303601, 0.39684955, 0.96541069, 0.06063692, 0.34103024],
       [0.58910018, 0.5749077 , 0.70292118, 0.26949598, 0.59303266],
       [0.47422108, 0.84892511, 0.99012256, 0.69055565, 0.87503472],
       [0.16547132, 0.4076408 , 0.23555816, 0.60089316, 0.18164584]])

In [42]:
np.random.randn(5)

array([ 0.01091487, -0.43679537, -0.52510287,  1.58697486,  0.62278422])

In [43]:
np.random.randn(4,5)

array([[-0.71205282,  0.74471088,  0.33719891, -0.67618097,  0.69687378],
       [-0.57194049,  0.03314929, -0.08027362,  1.14362503, -1.8587958 ],
       [-0.56416467,  0.29700519,  0.78044185,  0.49469542, -0.2564401 ],
       [-0.07128101, -0.1691744 , -1.44768839,  0.63055682,  1.13201887]])

In [46]:
np.random.randint(12)

10

In [48]:
np.random.randint(100)

96

In [63]:
np.random.randint(100,200,100)

array([160, 104, 131, 166, 125, 163, 149, 156, 191, 140, 146, 155, 196,
       180, 144, 110, 121, 153, 144, 134, 191, 153, 186, 122, 161, 105,
       164, 182, 177, 154, 182, 199, 101, 121, 159, 145, 157, 143, 116,
       187, 121, 169, 188, 102, 145, 126, 177, 184, 101, 106, 145, 151,
       197, 167, 142, 180, 198, 181, 116, 144, 124, 109, 175, 150, 174,
       132, 136, 145, 169, 144, 114, 180, 153, 166, 178, 164, 105, 118,
       188, 199, 166, 127, 148, 152, 194, 118, 110, 119, 105, 120, 116,
       120, 136, 199, 174, 160, 188, 166, 105, 155])

In [61]:
arr = np.arange(25)
print(arr)
print('----------------')
ranarr = np.random.randint(0,50,10)
print(ranarr)
print('----------------')
print(arr.reshape(5,5))


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
----------------
[27 42 32 34  7 23 25 30  1 44]
----------------
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [80]:
arr.max()

24

In [81]:
arr.min()

0

In [83]:
array = np.arange(20)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [86]:
array[4:10]

array([4, 5, 6, 7, 8, 9])

In [88]:
array[0:4]=100
array

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [96]:
new = np.arange(0,10)
slice_of_array=new[0:6]
print(slice_of_array)

[0 1 2 3 4 5]


In [93]:
slice_of_array[:]=90
print(slice_of_array)

[90 90 90 90 90 90]


In [97]:
new2 = new.copy()
print(new2)

[0 1 2 3 4 5 6 7 8 9]


In [99]:
TwoD = np.array([[2,3,4],[23,43,23],[23,23,46]])
print(TwoD)

[[ 2  3  4]
 [23 43 23]
 [23 23 46]]


In [103]:
print(TwoD[1:3])

[[23 43 23]
 [23 23 46]]


In [104]:
print(TwoD[0:2])

[[ 2  3  4]
 [23 43 23]]


In [105]:
print(TwoD[:2,0:1])

[[ 2]
 [23]]


In [108]:
print(TwoD[0:2,:2])

[[ 2  3]
 [23 43]]


In [67]:
my_post = np.arange(11)
print(my_post)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [89]:
I = np.zeros((4,5))
print(I)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [74]:
I = np.arange(20)
print(I.reshape(4,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [75]:
np.linspace(0,6,2)

array([0., 6.])

In [77]:
np.random.randn(4,5)

array([[-0.44750453,  1.07769912, -0.28105603,  1.04159006,  0.09830312],
       [ 0.65169724, -2.1054693 , -0.39887972,  0.16818427,  0.14189647],
       [ 0.06663565,  0.79460742, -0.06710688, -0.28313027, -0.34512605],
       [ 0.10977334, -0.03378183, -0.16143939, -0.25125914,  0.26857983]])